### PR TITLE
fix kernel 5.11 and above driver compilation

### PR DESCRIPTION
**Pull request by cydia2020**
Driver doesn't compile on kernel 5.11 and above, throws `error: implicit declaration of function ‘get_can_dlc’`

### CODE REVIEW

File: drivers/linux/panda.c [hunk 1]
```diff
@@ -283,7 +283,7 @@ static void panda_usb_process_can_rx(struct panda_dev_priv *priv_dev,
   //if (msg->dlc & MCBA_DLC_RTR_MASK)
   //  cf->can_id |= CAN_RTR_FLAG;
 
-  cf->can_dlc = get_can_dlc(msg->bus_dat_len & PANDA_DLC_MASK);
+  cf->can_dlc = (min_t(__u8, (msg->bus_dat_len & PANDA_DLC_MASK), 8));
```
Comment (adeebshihadeh) [inline drivers/linux/panda.c:286]: looks like this got renamed to `can_cc_dlc2len` https://lwn.net/Articles/836683/

Comment (cydia2020) [reply drivers/linux/panda.c:286]: Will try later

Comment (cydia2020) [reply drivers/linux/panda.c:286]: This does work and it seems to be reliable, but I'm not familiar with module development, so idk how I would go about differentiating between between different versions of different kernels.

Assistance in this regard would be appreciated.

**Comment by adeebshihadeh** [comment]
#765 supports the older macro and newer one
