### ISSUE TITLE
linux driver compilation problems with panda.c

### ISSUE THREAD

**Issue by flapse** [commaai/panda#746]
while compiling the linux driver I get a few errors for my Ubuntu 21:04 ( Kernel: Linux 5.13.9-051309-generic) computer

> > sudo make all
> sudo dkms build panda/0.0.1
> 
> Kernel preparation unnecessary for this kernel.  Skipping...
> 
> Building module:
> cleaning build area...
> make -j16 KERNELRELEASE=5.13.9-051309-generic -C /lib/modules/5.13.9-051309-generic/build M=/var/lib/dkms/panda/0.0.1/build...(bad exit status: 2)
> ERROR (dkms apport): binary package for panda: 0.0.1 not found
> Error! Bad return status for module build on kernel: 5.13.9-051309-generic (x86_64)
> Consult /var/lib/dkms/panda/0.0.1/build/make.log for more information.
> make: *** [Makefile:8: build] Fout 10

It seems to be related to changes in de socketcan files skb.h
A few functions got an additional argument of "frame_len_ptr".  (see source: https://github.com/torvalds/linux/blob/master/include/linux/can/skb.h ). These are the functions concerned:

int can_put_echo_skb(struct sk_buff *skb, struct net_device *dev, unsigned int idx, unsigned int frame_len);

unsigned int can_get_echo_skb(struct net_device *dev, unsigned int idx, unsigned int *frame_len_ptr);

void can_free_echo_skb(struct net_device *dev, unsigned int idx, unsigned int *frame_len_ptr);

How to solve this issue? How can I compile the linux driver for comma panda for my linux (Ubuntu

**Comment by flapse** [comment]
Hi Adeebshihadeh,

thanks for you quick response. I have tried your solution of #722 but this does not solve my problem. See log:

DKMS make.log for panda-0.0.1 for kernel 5.13.9-051309-generic (x86_64)
do 21 okt 2021 20:24:12 CEST
make: Map '/usr/src/linux-headers-5.13.9-051309-generic' wordt binnengegaan
  CC [M]  /var/lib/dkms/panda/0.0.1/build/panda.o
/var/lib/dkms/panda/0.0.1/build/panda.c: In function ‘panda_usb_write_bulk_callback’:
/var/lib/dkms/panda/0.0.1/build/panda.c:184:3: error: too few arguments to function ‘can_get_echo_skb’
  184 |   can_get_echo_skb(netdev, ctx->ndx);
      |   ^~~~~~~~~~~~~~~~
In file included from ./include/linux/can/dev.h:23,
                 from /var/lib/dkms/panda/0.0.1/build/panda.c:13:
./include/linux/can/skb.h:24:14: note: declared here
   24 | unsigned int can_get_echo_skb(struct net_device *dev, unsigned int idx,
      |              ^~~~~~~~~~~~~~~~
/var/lib/dkms/panda/0.0.1/build/panda.c: In function ‘panda_usb_start_xmit’:
/var/lib/dkms/panda/0.0.1/build/panda.c:458:3: error: too few arguments to function ‘can_put_echo_skb’
  458 |   can_put_echo_skb(skb, priv_inf->netdev, ctx->ndx);
      |   ^~~~~~~~~~~~~~~~
In file included from ./include/linux/can/dev.h:23,
                 from /var/lib/dkms/panda/0.0.1/build/panda.c:13:
./include/linux/can/skb.h:20:5: note: declared here
   20 | int can_put_echo_skb(struct sk_buff *skb, struct net_device *dev,
      |     ^~~~~~~~~~~~~~~~
/var/lib/dkms/panda/0.0.1/build/panda.c:483:3: error: too few arguments to function ‘can_free_echo_skb’
  483 |   can_free_echo_skb(priv_inf->netdev, ctx->ndx);
      |   ^~~~~~~~~~~~~~~~~
In file included from ./include/linux/can/dev.h:23,
                 from /var/lib/dkms/panda/0.0.1/build/panda.c:13:
./include/linux/can/skb.h:26:6: note: declared here
   26 | void can_free_echo_skb(struct net_device *dev, unsigned int idx,
      |      ^~~~~~~~~~~~~~~~~
make[1]: *** [scripts/Makefile.build:273: /var/lib/dkms/panda/0.0.1/build/panda.o] Fout 1
make: *** [Makefile:1859: /var/lib/dkms/panda/0.0.1/build] Fout 2
make: Map '/usr/src/linux-headers-5.13.9-051309-generic' wordt verlaten
